export const CURRENCIES = {
  NGN: 'NGN',
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  CAD: 'CAD',
  AUD: 'AUD',
  JPY: 'JPY',
  CNY: 'CNY',
  INR: 'INR',
  BRL: 'BRL',
  MXN: 'MXN',
  ZAR: 'ZAR',
  KRW: 'KRW',
  SGD: 'SGD',
  HKD: 'HKD',
  CHF: 'CHF',
  SEK: 'SEK',
  NOK: 'NOK',
  DKK: 'DKK',
  PLN: 'PLN',
  CZK: 'CZK',
  HUF: 'HUF',
  RUB: 'RUB',
  TRY: 'TRY',
  SAR: 'SAR',
  AED: 'AED',
  QAR: 'QAR',
  KWD: 'KWD',
  BHD: 'BHD',
  OMR: 'OMR',
  JOD: 'JOD',
  LBP: 'LBP',
  EGP: 'EGP',
  MAD: 'MAD',
  TND: 'TND',
  DZD: 'DZD',
  LYD: 'LYD',
  SDG: 'SDG',
  ETB: 'ETB',
  KES: 'KES',
  UGX: 'UGX',
  TZS: 'TZS',
  ZMW: 'ZMW',
  GHS: 'GHS',
  XOF: 'XOF',
  XAF: 'XAF',
  XCD: 'XCD',
  XPF: 'XPF',
  BTC: 'BTC',
  ETH: 'ETH',
  USDT: 'USDT',
  BNB: 'BNB'
} as const;

export const CURRENCY_SYMBOLS = {
  NGN: '₦',
  USD: '$',
  EUR: '€',
  GBP: '£',
  CAD: 'C$',
  AUD: 'A$',
  JPY: '¥',
  CNY: '¥',
  INR: '₹',
  BRL: 'R$',
  MXN: '$',
  ZAR: 'R',
  KRW: '₩',
  SGD: 'S$',
  HKD: 'HK$',
  CHF: 'CHF',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  PLN: 'zł',
  CZK: 'Kč',
  HUF: 'Ft',
  RUB: '₽',
  TRY: '₺',
  SAR: 'ر.س',
  AED: 'د.إ',
  QAR: 'ر.ق',
  KWD: 'د.ك',
  BHD: 'د.ب',
  OMR: 'ر.ع',
  JOD: 'د.أ',
  LBP: 'ل.ل',
  EGP: 'ج.م',
  MAD: 'د.م',
  TND: 'د.ت',
  DZD: 'د.ج',
  LYD: 'د.ل',
  SDG: 'ج.س',
  ETB: 'ብር',
  KES: 'KSh',
  UGX: 'USh',
  TZS: 'TSh',
  ZMW: 'ZK',
  GHS: 'GH₵',
  XOF: 'CFA',
  XAF: 'FCFA',
  XCD: 'EC$',
  XPF: 'CFP',
  BTC: '₿',
  ETH: 'Ξ',
  USDT: '₮',
  BNB: 'BNB'
} as const;

export const CURRENCY_NAMES = {
  NGN: 'Nigerian Naira',
  USD: 'US Dollar',
  EUR: 'Euro',
  GBP: 'British Pound',
  CAD: 'Canadian Dollar',
  AUD: 'Australian Dollar',
  JPY: 'Japanese Yen',
  CNY: 'Chinese Yuan',
  INR: 'Indian Rupee',
  BRL: 'Brazilian Real',
  MXN: 'Mexican Peso',
  ZAR: 'South African Rand',
  KRW: 'South Korean Won',
  SGD: 'Singapore Dollar',
  HKD: 'Hong Kong Dollar',
  CHF: 'Swiss Franc',
  SEK: 'Swedish Krona',
  NOK: 'Norwegian Krone',
  DKK: 'Danish Krone',
  PLN: 'Polish Złoty',
  CZK: 'Czech Koruna',
  HUF: 'Hungarian Forint',
  RUB: 'Russian Ruble',
  TRY: 'Turkish Lira',
  SAR: 'Saudi Riyal',
  AED: 'UAE Dirham',
  QAR: 'Qatari Riyal',
  KWD: 'Kuwaiti Dinar',
  BHD: 'Bahraini Dinar',
  OMR: 'Omani Rial',
  JOD: 'Jordanian Dinar',
  LBP: 'Lebanese Pound',
  EGP: 'Egyptian Pound',
  MAD: 'Moroccan Dirham',
  TND: 'Tunisian Dinar',
  DZD: 'Algerian Dinar',
  LYD: 'Libyan Dinar',
  SDG: 'Sudanese Pound',
  ETB: 'Ethiopian Birr',
  KES: 'Kenyan Shilling',
  UGX: 'Ugandan Shilling',
  TZS: 'Tanzanian Shilling',
  ZMW: 'Zambian Kwacha',
  GHS: 'Ghanaian Cedi',
  XOF: 'West African CFA Franc',
  XAF: 'Central African CFA Franc',
  XCD: 'East Caribbean Dollar',
  XPF: 'CFP Franc',
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  USDT: 'Tether',
  BNB: 'Binance Coin'
} as const;

export type Currency = typeof CURRENCIES[keyof typeof CURRENCIES];
export type CurrencySymbol = typeof CURRENCY_SYMBOLS[keyof typeof CURRENCY_SYMBOLS];
export type CurrencyName = typeof CURRENCY_NAMES[keyof typeof CURRENCY_NAMES]; 