export const ERROR_CODES = {
  // Authentication Errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',

  // Transaction Errors
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_PROCESSED: 'TRANSACTION_ALREADY_PROCESSED',
  TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  CARD_DECLINED: 'CARD_DECLINED',
  BANK_DECLINED: 'BANK_DECLINED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',

  // API Errors
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  WEBHOOK_FAILED: 'WEBHOOK_FAILED',
  WEBHOOK_TIMEOUT: 'WEBHOOK_TIMEOUT',

  // Database Errors
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DATABASE_ERROR: 'DATABASE_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',

  // Business Logic Errors
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  MERCHANT_INACTIVE: 'MERCHANT_INACTIVE',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',

  // System Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',

  // External Service Errors
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  PAYMENT_GATEWAY_ERROR: 'PAYMENT_GATEWAY_ERROR',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR',
  SMS_SERVICE_ERROR: 'SMS_SERVICE_ERROR',

  // Security Errors
  FRAUD_DETECTED: 'FRAUD_DETECTED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  IP_BLOCKED: 'IP_BLOCKED',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS'
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Token has expired',
  [ERROR_CODES.TOKEN_INVALID]: 'Invalid token provided',
  [ERROR_CODES.UNAUTHORIZED]: 'Unauthorized access',
  [ERROR_CODES.FORBIDDEN]: 'Access forbidden',
  [ERROR_CODES.ACCOUNT_LOCKED]: 'Account is locked',
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 'Email not verified',
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.INVALID_EMAIL]: 'Invalid email format',
  [ERROR_CODES.INVALID_PHONE]: 'Invalid phone number',
  [ERROR_CODES.INVALID_AMOUNT]: 'Invalid amount',
  [ERROR_CODES.INVALID_CURRENCY]: 'Invalid currency',
  [ERROR_CODES.INVALID_PAYMENT_METHOD]: 'Invalid payment method',
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: 'Transaction not found',
  [ERROR_CODES.TRANSACTION_ALREADY_PROCESSED]: 'Transaction already processed',
  [ERROR_CODES.TRANSACTION_EXPIRED]: 'Transaction has expired',
  [ERROR_CODES.INSUFFICIENT_FUNDS]: 'Insufficient funds',
  [ERROR_CODES.PAYMENT_DECLINED]: 'Payment was declined',
  [ERROR_CODES.CARD_DECLINED]: 'Card was declined',
  [ERROR_CODES.BANK_DECLINED]: 'Bank transfer was declined',
  [ERROR_CODES.NETWORK_ERROR]: 'Network error occurred',
  [ERROR_CODES.TIMEOUT_ERROR]: 'Request timeout',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.API_KEY_INVALID]: 'Invalid API key',
  [ERROR_CODES.API_KEY_EXPIRED]: 'API key has expired',
  [ERROR_CODES.WEBHOOK_FAILED]: 'Webhook delivery failed',
  [ERROR_CODES.WEBHOOK_TIMEOUT]: 'Webhook delivery timeout',
  [ERROR_CODES.DUPLICATE_ENTRY]: 'Duplicate entry found',
  [ERROR_CODES.RECORD_NOT_FOUND]: 'Record not found',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error occurred',
  [ERROR_CODES.CONNECTION_ERROR]: 'Connection error',
  [ERROR_CODES.MERCHANT_NOT_FOUND]: 'Merchant not found',
  [ERROR_CODES.MERCHANT_INACTIVE]: 'Merchant account is inactive',
  [ERROR_CODES.SUBSCRIPTION_EXPIRED]: 'Subscription has expired',
  [ERROR_CODES.PLAN_LIMIT_EXCEEDED]: 'Plan limit exceeded',
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: 'Feature not available',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [ERROR_CODES.MAINTENANCE_MODE]: 'Service under maintenance',
  [ERROR_CODES.CONFIGURATION_ERROR]: 'Configuration error',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
  [ERROR_CODES.PAYMENT_GATEWAY_ERROR]: 'Payment gateway error',
  [ERROR_CODES.EMAIL_SERVICE_ERROR]: 'Email service error',
  [ERROR_CODES.SMS_SERVICE_ERROR]: 'SMS service error',
  [ERROR_CODES.FRAUD_DETECTED]: 'Fraud detected',
  [ERROR_CODES.SUSPICIOUS_ACTIVITY]: 'Suspicious activity detected',
  [ERROR_CODES.IP_BLOCKED]: 'IP address blocked',
  [ERROR_CODES.TOO_MANY_ATTEMPTS]: 'Too many attempts'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
export type ErrorMessage = typeof ERROR_MESSAGES[keyof typeof ERROR_MESSAGES]; 