import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Simple favicon generator script
 * Converts your logo to proper favicon formats
 * 
 * Usage: node generate-favicon.js
 */

// Configuration
const LOGO_PATH = path.join(__dirname, 'public', 'transactlab', '4.png');
const OUTPUT_DIR = path.join(__dirname, 'public');
const FAVICON_SIZES = [16, 32, 48, 96, 144, 192, 512];

console.log('🎨 TransactLab Favicon Generator');
console.log('================================');

// Check if logo exists
if (!fs.existsSync(LOGO_PATH)) {
  console.error('❌ Logo not found at:', LOGO_PATH);
  console.log('Please make sure your logo exists at the specified path.');
  process.exit(1);
}

console.log('✅ Logo found at:', LOGO_PATH);

// Create HTML snippet for multiple favicon formats
const generateFaviconHTML = () => {
  return `
<!-- Favicon generated by TransactLab Favicon Generator -->
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="512x512" href="/android-chrome-512x512.png">
<link rel="manifest" href="/site.webmanifest">
<meta name="theme-color" content="#ffffff">
`.trim();
};

// Create site.webmanifest
const generateWebManifest = () => {
  return {
    "name": "TransactLab",
    "short_name": "TransactLab",
    "description": "Developer sandbox for payment gateway testing",
    "icons": [
      {
        "src": "/android-chrome-192x192.png",
        "sizes": "192x192",
        "type": "image/png"
      },
      {
        "src": "/android-chrome-512x512.png",
        "sizes": "512x512",
        "type": "image/png"
      }
    ],
    "theme_color": "#ffffff",
    "background_color": "#ffffff",
    "display": "standalone"
  };
};

// Instructions for manual conversion
const printInstructions = () => {
  console.log('\n📋 Manual Favicon Generation Instructions:');
  console.log('==========================================');
  console.log('Since we can\'t automatically resize images in Node.js without additional packages,');
  console.log('here are the steps to create your favicons manually:\n');
  
  console.log('1. 🖼️  Open your logo:', LOGO_PATH);
  console.log('2. 📏  Create these sizes and save them as PNG:');
  FAVICON_SIZES.forEach(size => {
    console.log(`   - ${size}x${size}px → save as favicon-${size}x${size}.png`);
  });
  console.log('   - 180x180px → save as apple-touch-icon.png');
  console.log('   - 192x192px → save as android-chrome-192x192.png');
  console.log('   - 512x512px → save as android-chrome-512x512.png');
  
  console.log('\n3. 🔧  Tools you can use:');
  console.log('   - Online: https://realfavicongenerator.net/');
  console.log('   - Photoshop/GIMP: Resize and export');
  console.log('   - Canva: Upload and resize');
  console.log('   - VS Code Extensions: Image Preview + export');
  
  console.log('\n4. 📁  Save all files to:', OUTPUT_DIR);
  
  console.log('\n5. 📝  Add this HTML to your <head> section:');
  console.log(generateFaviconHTML());
  
  console.log('\n6. 📱  Create site.webmanifest file:');
  console.log(JSON.stringify(generateWebManifest(), null, 2));
};

// Create output directory if it doesn't exist
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  console.log('📁 Created output directory:', OUTPUT_DIR);
}

// Generate files
try {
  // Create HTML snippet file
  const htmlSnippet = generateFaviconHTML();
  fs.writeFileSync(path.join(OUTPUT_DIR, 'favicon-snippet.html'), htmlSnippet);
  console.log('✅ Created favicon-snippet.html');
  
  // Create web manifest
  const manifest = generateWebManifest();
  fs.writeFileSync(
    path.join(OUTPUT_DIR, 'site.webmanifest'), 
    JSON.stringify(manifest, null, 2)
  );
  console.log('✅ Created site.webmanifest');
  
  // Create a simple ICO file placeholder (just copy the original logo)
  console.log('📋 Copying your logo as a temporary favicon...');
  fs.copyFileSync(LOGO_PATH, path.join(OUTPUT_DIR, 'favicon-temp.png'));
  console.log('✅ Created favicon-temp.png (temporary)');
  
  printInstructions();
  
  console.log('\n🎉 Favicon generation setup complete!');
  console.log('Follow the manual instructions above to create your favicon files.');
  
} catch (error) {
  console.error('❌ Error generating favicon files:', error.message);
}

console.log('\n💡 Quick Tip: Use https://realfavicongenerator.net/ for automatic favicon generation!');
